name: NodeJS with Webpack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        os: [macos, ubuntu, windows]
        node-version: [14.x]
    runs-on: ${{ matrix.os }}-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: checkout
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB }}
      run: |
        git remote update
        git fetch
        git checkout download

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        git checkout main
        npm install
        npm run package
        npm run make

    - name: move
      run: |
        cp -r ./out/make/zip/* .

    - name: checkout
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB }}
      run: |
        git remote update
        git fetch
        git checkout download

    - name: push
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_GITHUB }}
      run: |
        git config --local user.name Sotaneum
        git config --local user.email gnyontu39@gmail.com
        git add .
        git commit -m "update"
        git push
